### ISSUE TITLE
Интерфейсы в 1С

### ISSUE THREAD

**Issue by DoublesunRUS** [marmyshev/edt-plugins#15]
БСП содержит в себе механизмы, которые по сути требуют от подключенного объекта реализацию некоторого интерфейса. Например https://its.1c.ru/db/bsp314doc#content:4:1:issogl2_%D0%BD%D0%B0%D1%81%D1%82%D1%80%D0%BE%D0%B9%D0%BA%D0%B037

То есть объект подключенный к механизму должен содержать внутри модулей некоторые методы и содержать в объектах некий набор табличных частей и реквизитов.

Пробовал на примере подсистемы Подключаемые команды сделать такие проверки:
https://github.com/DoublesunRUS/ru.capralow.dt.ssl.checks

В процессе реализации понял:
1. Ручное прописывание проверок очень трудоемкое
2. Очень много повторяющегося кода

У меня сложилось мнение, что данную задачу можно решить через декларативное описание подобных интерфейсов.
Так как БСП не является открытой библиотекой, то в качестве декларативного описания нужно использовать внешний файл. Например json или yaml.

**Comment by marmyshev** [comment]
Я с идеей согласен, но этот механизм не является БСПшным - выставить публичный интерфейс (абстракцию) может кто угодно для любого механизма, который потом потребует имплементации в других объектах.

Да, в БСП механизмы этим особенно часто пользуются... Но в ERP например тоже есть таки интерфейсы и реализации.

**Comment by DoublesunRUS** [comment]
В ЗУП тоже есть такие механизмы. Просто в БСП это явно в документации по внедрению написано, поэтому проще начинать разработку тому, кто не знает специфики ЗУП или ERP.

**Comment by RedMammoth** [comment]
А что если описывать не json/yaml, а где-нибудь хранить объекты-шаблоны, их и редактировать было бы проще уже имеющимися редакторами форм, модулей и т.п. , и, как мне кажется, реализовывать проверки на соблюдение будет проще

**Comment by RedMammoth** [comment]
В самой конфигурации наверное не хорошо, но почему бы и не создать подсистему для интерфейсов, каждая вложенная подсистема по названию интерфейса, а объекты, включенные во вложенную подсистему - контракт (реквизиты на формах, процедуры, реквизиты объектов, табличные части и т.д.) . Какие-то особенности можно вложить в префиксы/суффиксы объектов

**Comment by marmyshev** [comment]
Еще одна из идей реализации интерфейсов:

1. Объявляем интерфейс

```yaml
name: МойВолшебныйИнтерфейс
  baseType: СправочникМенеджер
  methods:
    Метод1:
      returns: Строка
      parameters:
        - Параметр1:
           type: Число 
        - Параметр2:
           type: СправочникСсылка.Товары
        - Параметр3:
          type: Интерфейс.МойВторойИнтерфейс
```

```yaml
name: МойВторойИнтерфейс
baseType: УправляемаяФорма
  attributes:
   Атрибут1:
    type: СправочникСсылка.Товары
...
```

2. Используем интерфейс в коде:

```bsl
// Параметры:
// ОбъектИнтерфейса - См. Интерфейс.МойВолшебныйИнтерфейс - тут в док коменте ссылка на интерфейс
// ОбъектИнтерфейса2 - См. Интерфейсы.МойВторойИнтерфейс
Процедура Тест(ОбъектИнтерфейса, ОбъектИнтерфейса2) Экспорт

ОбъектИнтерфейса.Метод1(12, Ссылка, ОбъектИнтерфейса2);

```

плагин будет генерит по описанию специфичные типы и загружать их в систему ЕДТ. 
Расширить ссылочную систему документирующих комментариев - чтобы подгружали эти типы.

**Comment by marmyshev** [comment]
Пример того как это может работать

<img width="741" alt="image" src="https://user-images.githubusercontent.com/4069973/150655834-cf127b51-ff23-47da-a08c-302ddac1ffa0.png">

**Comment by marmyshev** [comment]
Модель файлов описания интерфейса для модуля:

```yaml
name: МойВолшебныйИнтерфейс.ВторичныйИнтерфейс # уникальное имя интерфейса с поддержкой name-space
  parentType: СправочникМенеджер # базовый/родительский тип к которому добавляются методы и свойства
  methods: # поддерживается добавление методов, если в родительском типе их нет
    Метод1:
      returns: Строка # Возвращаемый тип, означает метод является функцией
      export: true # признак что метод должен быть экспортным
      parameters: # описание параметров метода
        - Параметр1:
           type: Число 
        - Параметр2:
           type: СправочникСсылка.Товары
        - Параметр3:
          type: Интерфейс.МойВторойИнтерфейс
        - Параметр4:
          typeLink: ОбщегоНазначения.ФункцияКонструкторТипа # Любая ссылка на тип или объект, поддерживаемый в док.комментах
```

Интерфейс для описания объекта метаданных

```yaml
name: ИнтерфейсаОбъектаМД # уникальное имя интерфейса с поддержкой name-space
  parentType: СправочникОбъект # базовый/родительский тип к которому добавляются методы и свойства
  methods: # поддерживается добавление методов, если в родительском типе их нет
    ПриЗаписи: # Возможно указывать метод, существующий в типе, описывать сигнатуру метода не нужно
       # Выполняется поиск кода в тексте метода
      containsCode: | 
        Свойства.ПриЗаписи(ЭтотОбъект, Отказ);
  attributes: # возможность описания реквизитов объекта
    МойРеквизит:
      type: СправочникСсылка.Товары
  tabularSections: # описание наличия таб.частей и их реквизитов
    Товары:
      attributes:
        Товар:
          type: СправочникСсылка.Товары
        Количество:
          type: Число(15,3)
        Цена:
          type: ОпределяемыйТип.Валютный
        Сумма:
          type: ОпределяемыйТип.Валютный
  commands: # описание команд объекта
    МояКоманда: # имя команды и далее свойства команды...
```

Интерфейс для описания форм

```yaml
name: КонтактнаяИнформация.ФормаКИ # уникальное имя интерфейса с поддержкой name-space
  parentType: УправляемаяФорма # базовый/родительский тип к которому добавляются методы и свойства
  methods: # поддерживается добавление методов в модуля формы, если в родительском типе их нет
    Метод1:
      returns: Строка # Возвращаемый тип, означает метод является функцией
      export: true # признак что метод должен быть экспортным
      parameters: # описание параметров метода
        - Параметр1:
           type: Число 
        - Параметр2:
           ...
  attributes: # реквизиты формы
   ИмяРеквизитаФормы:
     type: ТаблицаЗначения
  items: # элементы формы, которые должны присутствовать на форме
    ДополнительнаяГруппаКИ
      itemType: FormGroup
```
